try:
    print('try')
except:
    try:
        print('inner try')
    except:
        print('inner except')